### ISSUE TITLE
Gradle Project Support is Broken

### ISSUE THREAD

**Issue by tusharjoshi** [tusharjoshi/nbrunwithargs#8]
Using Java 14 and Apache NetBeans 12.0 the class for Gradle Project has changed and hence the Gradle Support is broken.
Update to reflection based  code in GradleCommandHandler is needed 

cc: @kkofler

**Comment by kkofler** [comment]
We have tested more than one version, but not yet 12.0.

Since the code is using reflection, it should be possible to make it work with both old and new versions at the same time.

**Comment by kkofler** [comment]
So `Constants.GRADLEPROJECT` is wrong for NetBeans 12.0 too? Then not only `GradleCommandHandler` has to change, but also `CommandHandler` and `ProjectAction`, to support 2 different constants (e.g., `Constants.GRADLEPROJECT_OLD` and `Constants.GRADLEPROJECT`).

**Comment by tusharjoshi** [comment]
I was thinking of uploading the plugin again to the current plugin catalog.  To do that we will need the plugin to work with the currently released latest version which is NetBeans 12.0

I can have a look into the code this weekend to fix it, if you happen to achieve the solution before that let me know.

**Comment by tusharjoshi** [comment]
Your comment tells me that the current code works for NetBeans versions below 12.0, if we have to keep the plugin working for current version as well as versions below 12.0 then we will have to detect the NetBeans version also to branch out to two different logic blocks

One solution to branch out can be having two separate concrete classes for CommandHandler
1) GradleCommandHandler12
2) GradleCommandHandler

**Comment by kkofler** [comment]
Unfortunately, I don't really have the time to look further into this right now.

Depending on how big the API changes are, it may make sense to use two separate command handler classes as you suggest, or it may be easier to do it in one class.

**Comment by kkofler** [comment]
FYI, I am going to look into finally making this work with NetBeans 12.x, at least with the latest 12.6, ASAP.

**Comment by kkofler** [comment]
What I can tell so far is that the Maven support still works unchanged, which is good news, but kinda surprises me because it needs to poke around in non-API classes just as much as the Gradle one.

But Gradle is the one we mostly care about at DAGOPT and that one definitely needs (porting) work. It is just that we had been stuck on NetBeans 8.2 so far for various reasons, so I was not able to justify spending time on porting the plugin to newer versions on company time so far. Now we are finally looking into upgrading NetBeans and the plugin appears to be the main blocker, which explains the sudden change in priorities. I am on it.

**Comment by kkofler** [comment]
As far as I can tell, the Gradle module, which is now integrated (apparently since NetBeans 10) whereas it was a plugin in NetBeans 8, is structured completely differently now. The `GradleCommandHandler` is really going to be a rewrite more than a port. I have started working on it.

**Comment by kkofler** [comment]
I got this sorta working, **but** so far I do not have a way to actually pass command-line arguments without adding custom support for it in the Gradle files. At least the runSingle/debugSingle tasks that NetBeans 12 generates do not seem to honor `-PcmdLineArgs=…`.

**Comment by kkofler** [comment]
The source code is always the best documentation…
https://github.com/apache/netbeans/blob/release126/extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.groovy#L36
`-PrunArgs=…` is the magic.

**Comment by tusharjoshi** [comment]
I am glad to see this feature getting in shape.  Thanks for all the efforts, will be glad to merge the PR when it is ready.
